apiVersion: v1
data:
  mysql_password: c2VjcmV0MTIz
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-pass
type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
  labels: {{ include "common.labels.svc" . | nindent 6 }}
spec:
  storageClassName: premium-ssd1
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {{ include "common.labels.svc" . | nindent 6 }}
  name: {{ .Release.Name }}-mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: premium-ssd1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
  labels: {{ include "common.labels.svc" . | nindent 6 }}
spec:
  serviceName: "mysql"
  selector:
    matchLabels: {{ include "common.labels.mysql" . | nindent 8 }}
  template:
    metadata:
      labels: {{ include "common.labels.mysql" . | nindent 10 }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql_password
              name: {{ .Release.Name }}-mysql-pass
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: {{ .Values.portmysql }}
          name: mysql
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "common.labels.svc" . | nindent 6 }}
  name: {{ .Release.Name }}-mysql
spec:
  ports:
  - port:  {{ .Values.portmysql }}
    protocol: TCP
    targetPort:  {{ .Values.portmysql }}
  selector: {{ include "common.labels.mysql" . | nindent 6 }}
  type: ClusterIP
