apiVersion: v1
data:
  mysql_password: secret123
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-configmap
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "common.labels.svc" . | nindent 6 }}
spec:
  selector:
    matchLabels: {{ include "common.labels" . | nindent 8 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels: {{ include "common.labels" . | nindent 10 }}
    spec:
      containers:
        - image: kevindollasbay/baobi01:v1
          name: {{ .Release.Name }}-image
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name:  {{ .Release.Name }}-mysql-configmap
                  key: mysql_password
          ports:
            - containerPort: {{ .Values.port }}
              name: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "common.labels.svc" . | nindent 6 }}
spec:
  ports:
    - port: {{ .Values.port }}
  selector: {{ include "common.labels" . | nindent 6 }}
  type: LoadBalancer
